version: "3.9"

services:
    db:
        image: mysql
        container_name: data_base
        restart: on-failure
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    phpmyadmin:
        image: phpmyadmin
        container_name: PhpMyAdmin
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8000:80
        environment:
            PMA_HOST: db

    web:
        build: php
        container_name: portfolio_php
        restart: on-failure
        volumes:
            - ./app:/app:rw
        ports:
            - 8080:80

volumes:
    db-data:
